export const developmentAnswers = {
  agent_name: 'Frontend Quality Guardian',
  purpose: 'pr-review',
  objective: 'Revisar pull requests del frontend y proponer correcciones pequeñas sin hacer merge automático.',
  success_criteria: 'Cada pull request recibe hallazgos priorizados, evidencia y pruebas sugeridas.',
  project_stage: 'existing',
  technologies: ['typescript', 'react', 'nextjs', 'postgresql'],
  architecture: 'modular-monolith',
  repository_provider: 'github',
  environment: 'development',
  development_setup: 'docker-compose',
  ci_cd: ['github-actions'],
  security_controls: ['least-privilege', 'container-scan', 'secrets-manager'],
  capabilities: ['read-repository', 'edit-code', 'run-tests', 'review-pr'],
  autonomy: 'advisory',
  knowledge_enabled: true,
  knowledge_sources: ['repository-docs', 'source-code'],
  pr_review_enabled: true,
  pr_review_focus: ['correctness', 'security', 'tests', 'architecture'],
  agent_targets: ['agents-md', 'cursor', 'devin-desktop', 'coderabbit', 'kilo-code', 'kiro', 'portable'],
  hooks_enabled: true,
  skills_enabled: true,
  skills_focus: 'custom',
  // Ids for `skills_selection` come from the curated skills catalog, which is
  // the source of the catalog's `skill` category (see src/creator/catalog.ts).
  skills_selection: ['debug-diagnose', 'security-code-review'],
  mcps_enabled: true,
  // Ids for `mcps_selection` come from the curated MCP catalog, which is the
  // source of the catalog's `mcp` category (see src/creator/catalog.ts).
  mcps_selection: ['github-mcp-server'],
  testing_tools: ['unit-tests', 'e2e-tests', 'sast'],
};

export const productionAnswers = {
  agent_name: 'EC2 Operations Advisor',
  purpose: 'operations',
  objective: 'Diagnosticar incidentes de una API en EC2 y preparar planes de remediación reversibles.',
  success_criteria: 'Cada incidente produce evidencia, hipótesis, pasos de verificación y plan de rollback.',
  project_stage: 'existing',
  technologies: ['typescript', 'express', 'sqlite', 'redis'],
  architecture: 'microservices',
  repository_provider: 'github',
  environment: 'production',
  deployment_target: 'aws-ec2',
  container_platforms: ['docker'],
  ci_cd: ['github-actions'],
  infrastructure: ['terraform', 'ansible'],
  observability: ['opentelemetry', 'cloudwatch', 'sentry'],
  security_controls: ['least-privilege', 'secrets-manager', 'sbom'],
  capabilities: ['read-repository', 'inspect-infrastructure', 'operate-production'],
  autonomy: 'assisted',
  human_approval: true,
  knowledge_enabled: true,
  knowledge_sources: ['repository-docs', 'runbooks'],
  pr_review_enabled: false,
  agent_targets: ['agents-md', 'devin-desktop', 'coderabbit', 'portable'],
  hooks_enabled: true,
  skills_enabled: true,
  skills_focus: 'operations',
  mcps_enabled: false,
};
