services:
  - type: web
    name: artemisa-backend
    runtime: docker
    repo: https://github.com/VECTORG99/Artemisa
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: AUTH_REQUIRED
        value: 'true'
      - key: ARTEMISA_API_KEYS
        generateValue: true
      - key: BYPASS_SECRET
        generateValue: true
      - key: METRICS_SECRET
        generateValue: true
