import type { CreatorAnswers } from '@huascar/types';

export interface CreatorPreset {
  id: string;
  name: string;
  tagline: string;
  description: string;
  /** Complete, valid answers for the current WORKFLOW_VERSION (see
   * src/creator/decisionTree.ts). Every required question for the branches
   * these answers activate is filled in — /evaluate should report
   * progress.complete === true for each preset as-is. */
  answers: CreatorAnswers;
}

/**
 * Curated, ready-to-use agent configurations — issue #390's "Presets" mode.
 * These are plain data (no backend concept of presets exists, and none is
 * needed: a preset is just a complete, pre-filled CreatorAnswers object).
 * Selecting one sends it straight to /evaluate for validation, then Review,
 * where every answer remains editable before generating — "llegar y copiar,
 * con la variación que el usuario quiera" per project direction.
 */
export const CREATOR_PRESETS: CreatorPreset[] = [
  {
    id: 'pr-reviewer-github',
    name: 'Revisor de Pull Requests',
    tagline: 'GitHub + GitHub Actions',
    description: 'Analiza cada PR, prioriza hallazgos por severidad y nunca hace merge por sí mismo.',
    answers: {
      agent_name: 'pr-reviewer',
      purpose: 'pr-review',
      objective: 'Revisar cada pull request, explicar riesgos con evidencia y proponer cambios sin fusionar.',
      success_criteria: 'Cada PR recibe un informe priorizado por severidad y ningún falso positivo crítico.',
      project_stage: 'existing',
      technologies: ['typescript', 'javascript'],
      architecture: 'modular-monolith',
      repository_provider: 'github',
      environment: 'development',
      development_setup: 'docker-compose',
      ci_cd: ['github-actions'],
      security_controls: ['secrets-manager', 'least-privilege'],
      capabilities: ['read-repository', 'review-pr', 'manage-issues'],
      autonomy: 'advisory',
      knowledge_enabled: true,
      knowledge_sources: ['repository-docs', 'source-code'],
      pr_review_enabled: true,
      pr_review_focus: ['correctness', 'security', 'architecture', 'tests'],
      agent_targets: ['agents-md', 'coderabbit', 'kiro'],
      hooks_enabled: true,
      skills_enabled: true,
      skills_focus: 'development',
      mcps_enabled: false,
    },
  },
  {
    id: 'dev-agent-node',
    name: 'Agente de Desarrollo',
    tagline: 'Node.js + TypeScript',
    description: 'Lee el repositorio, propone parches revisables y ejecuta pruebas allowlisted.',
    answers: {
      agent_name: 'dev-assistant',
      purpose: 'coding',
      objective:
        'Implementar y corregir código siguiendo las convenciones del repositorio, sin aplicar cambios automáticamente.',
      success_criteria: 'Los parches propuestos pasan lint y tests sin intervención manual adicional.',
      project_stage: 'existing',
      technologies: ['typescript', 'javascript'],
      architecture: 'modular-monolith',
      repository_provider: 'github',
      environment: 'development',
      development_setup: 'docker-compose',
      testing_tools: ['unit-tests', 'integration-tests'],
      ci_cd: ['github-actions'],
      security_controls: ['least-privilege'],
      capabilities: ['read-repository', 'edit-code', 'run-tests'],
      autonomy: 'assisted',
      human_approval: true,
      knowledge_enabled: true,
      knowledge_sources: ['repository-docs', 'source-code'],
      pr_review_enabled: false,
      agent_targets: ['agents-md', 'cursor', 'devin-desktop', 'kiro', 'portable'],
      hooks_enabled: true,
      skills_enabled: true,
      skills_focus: 'development',
      mcps_enabled: false,
    },
  },
  {
    id: 'devops-platform',
    name: 'Agente DevOps',
    tagline: 'CI/CD + Kubernetes + Terraform',
    description: 'Documenta quality gates, IaC y promoción entre entornos sin desplegar automáticamente.',
    answers: {
      agent_name: 'platform-agent',
      purpose: 'devops',
      objective: 'Automatizar y documentar pipelines de CI/CD, infraestructura como código y promoción entre entornos.',
      success_criteria: 'Cada cambio de infraestructura pasa por plan/apply revisado y queda documentado.',
      project_stage: 'existing',
      technologies: ['go', 'typescript'],
      architecture: 'microservices',
      repository_provider: 'github',
      environment: 'both',
      development_setup: 'devcontainer',
      testing_tools: ['integration-tests', 'contract-tests'],
      deployment_target: 'aws-eks',
      container_platforms: ['docker', 'kubernetes', 'helm'],
      ci_cd: ['github-actions', 'argocd'],
      infrastructure: ['terraform'],
      observability: ['opentelemetry', 'cloudwatch'],
      security_controls: ['least-privilege', 'secrets-manager', 'policy-as-code'],
      capabilities: ['read-repository', 'inspect-infrastructure', 'automate-workflows', 'generate-reports'],
      autonomy: 'assisted',
      human_approval: true,
      knowledge_enabled: true,
      knowledge_sources: ['repository-docs', 'runbooks'],
      pr_review_enabled: false,
      agent_targets: ['agents-md', 'kiro'],
      hooks_enabled: true,
      skills_enabled: true,
      skills_focus: 'operations',
      mcps_enabled: false,
    },
  },
  {
    id: 'production-ops-aws',
    name: 'Agente de Operación',
    tagline: 'Producción en AWS EC2',
    description: 'Diagnóstico y observabilidad en producción con aprobación humana obligatoria.',
    answers: {
      agent_name: 'ops-responder',
      purpose: 'operations',
      objective: 'Diagnosticar incidentes en producción, correlacionar métricas/logs y proponer remediación.',
      success_criteria: 'Cada incidente recibe un diagnóstico con evidencia antes de cualquier acción correctiva.',
      project_stage: 'existing',
      technologies: ['python', 'go'],
      architecture: 'microservices',
      repository_provider: 'github',
      environment: 'production',
      deployment_target: 'aws-ec2',
      container_platforms: ['docker'],
      ci_cd: ['github-actions'],
      infrastructure: ['terraform'],
      observability: ['opentelemetry', 'cloudwatch', 'prometheus-grafana'],
      security_controls: ['least-privilege', 'secrets-manager', 'oidc'],
      capabilities: ['inspect-infrastructure', 'operate-production', 'generate-reports'],
      autonomy: 'assisted',
      human_approval: true,
      knowledge_enabled: true,
      knowledge_sources: ['runbooks', 'rag-vector-store'],
      pr_review_enabled: false,
      agent_targets: ['agents-md'],
      hooks_enabled: true,
      skills_enabled: true,
      skills_focus: 'operations',
      mcps_enabled: false,
    },
  },
  {
    id: 'security-scanner',
    name: 'Agente de Seguridad',
    tagline: 'SAST + supply chain',
    description: 'Escanea código, dependencias y configuración; nunca ejecuta remediación automática.',
    answers: {
      agent_name: 'security-scanner',
      purpose: 'security',
      objective: 'Escanear código, dependencias y configuración en busca de vulnerabilidades y malas prácticas.',
      success_criteria: 'Cada hallazgo incluye severidad, evidencia y remediación sugerida.',
      project_stage: 'existing',
      technologies: ['typescript', 'python'],
      architecture: 'modular-monolith',
      repository_provider: 'github',
      environment: 'development',
      development_setup: 'docker-compose',
      testing_tools: ['sast', 'dependency-scan'],
      ci_cd: ['github-actions'],
      security_controls: ['sbom', 'container-scan', 'least-privilege'],
      capabilities: ['read-repository', 'scan-vulnerabilities', 'audit-compliance', 'generate-reports'],
      autonomy: 'advisory',
      knowledge_enabled: true,
      knowledge_sources: ['repository-docs', 'source-code'],
      pr_review_enabled: true,
      pr_review_focus: ['security'],
      agent_targets: ['agents-md', 'kiro'],
      hooks_enabled: true,
      skills_enabled: true,
      skills_focus: 'security',
      mcps_enabled: false,
    },
  },
  {
    id: 'data-ai-rag',
    name: 'Agente de Datos e IA',
    tagline: 'RAG + pipelines de datos',
    description: 'Gestiona fuentes de conocimiento vectorial y pipelines de datos con calidad verificable.',
    answers: {
      agent_name: 'data-ai-agent',
      purpose: 'data-ai',
      objective: 'Mantener pipelines de datos y un corpus RAG actualizado, con verificación de calidad en cada paso.',
      success_criteria: 'Las consultas RAG devuelven fuentes verificables y los pipelines fallan de forma explícita.',
      project_stage: 'existing',
      technologies: ['python'],
      architecture: 'data-pipeline',
      repository_provider: 'github',
      environment: 'both',
      development_setup: 'docker-compose',
      testing_tools: ['integration-tests'],
      deployment_target: 'aws-lambda',
      ci_cd: ['github-actions'],
      infrastructure: ['terraform'],
      observability: ['opentelemetry', 'cloudwatch'],
      security_controls: ['least-privilege', 'secrets-manager'],
      capabilities: ['read-repository', 'analyze-data', 'generate-reports'],
      autonomy: 'assisted',
      human_approval: true,
      knowledge_enabled: true,
      knowledge_sources: ['rag-vector-store', 'repository-docs'],
      pr_review_enabled: false,
      agent_targets: ['agents-md'],
      hooks_enabled: true,
      skills_enabled: true,
      skills_focus: 'data-ai',
      mcps_enabled: false,
    },
  },
  {
    id: 'docs-maintainer',
    name: 'Agente de Documentación',
    tagline: 'Guías + changelogs + runbooks',
    description: 'Mantiene documentación técnica alineada con el código y genera changelogs.',
    answers: {
      agent_name: 'docs-maintainer',
      purpose: 'documentation',
      objective: 'Mantener README, guías de arquitectura y changelogs alineados con el estado real del código.',
      success_criteria: 'La documentación referencia código vigente y cada release incluye un changelog verificable.',
      project_stage: 'existing',
      technologies: ['typescript', 'javascript'],
      architecture: 'modular-monolith',
      repository_provider: 'github',
      environment: 'development',
      development_setup: 'local',
      ci_cd: ['github-actions'],
      security_controls: ['least-privilege'],
      capabilities: ['read-repository', 'generate-reports'],
      autonomy: 'advisory',
      knowledge_enabled: true,
      knowledge_sources: ['repository-docs', 'source-code'],
      pr_review_enabled: false,
      agent_targets: ['portable', 'kiro'],
      hooks_enabled: false,
      skills_enabled: true,
      skills_focus: 'documentation',
      mcps_enabled: false,
    },
  },
  {
    id: 'portable-minimal',
    name: 'Agente Portable Mínimo',
    tagline: 'AGENTS.md sin dependencias',
    description: 'La base más simple: identidad, objetivo y capacidades de lectura, sin integraciones extra.',
    answers: {
      agent_name: 'minimal-agent',
      purpose: 'coding',
      objective: 'Asistir en tareas de desarrollo puntuales sin integraciones adicionales.',
      success_criteria: 'El agente responde consultas sobre el código con contexto correcto del repositorio.',
      project_stage: 'existing',
      technologies: ['typescript'],
      architecture: 'monolith',
      repository_provider: 'local-repository',
      environment: 'development',
      development_setup: 'local',
      ci_cd: ['github-actions'],
      security_controls: ['least-privilege'],
      capabilities: ['read-repository'],
      autonomy: 'advisory',
      knowledge_enabled: false,
      pr_review_enabled: false,
      agent_targets: ['portable'],
      hooks_enabled: false,
      skills_enabled: false,
      mcps_enabled: false,
    },
  },
];
