/**
 * Curated, versioned catalog of LLM models for agent configuration.
 *
 * The catalog is orientative: the user configures provider and API key
 * separately. Prices are not hardcoded (they change constantly); `tier`
 * is the proxy for cost positioning.
 *
 * Context windows and max output reflect documented specs as of July 2025.
 */

export interface ModelCatalogItem {
  id: string;
  name: string;
  provider: 'openai' | 'anthropic' | 'google' | 'meta' | 'mistral' | 'cohere' | 'deepseek' | 'open-source';
  description: string;
  contextWindow: number;
  maxOutput: number;
  tier: 'frontier' | 'mid' | 'efficient' | 'local';
  strengths: string[];
  supportsTools: boolean;
  supportsVision: boolean;
  supportsStreaming: boolean;
  localOnly?: boolean;
  tags: string[];
}

export const MODELS_CATALOG_VERSION = '1.0.0';

export const modelsCatalog: ModelCatalogItem[] = [
  // ─── OpenAI (10) ──────────────────────────────────────────────────────
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'openai',
    description: 'Modelo flagship de OpenAI con 1M de contexto, optimizado para coding e instrucciones complejas.',
    contextWindow: 1_000_000,
    maxOutput: 32_768,
    tier: 'frontier',
    strengths: ['coding', 'instruction-following', 'long-context', 'tool-use'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['openai', 'flagship', 'coding'],
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    provider: 'openai',
    description: 'Versión rápida y económica de GPT-4.1 con el mismo contexto de 1M.',
    contextWindow: 1_000_000,
    maxOutput: 32_768,
    tier: 'mid',
    strengths: ['speed', 'tool-calling', 'cost-efficient', 'long-context'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['openai', 'fast', 'balanced'],
  },
  {
    id: 'gpt-4.1-nano',
    name: 'GPT-4.1 Nano',
    provider: 'openai',
    description: 'El más rápido de la familia 4.1, ideal para clasificación y extracción.',
    contextWindow: 1_000_000,
    maxOutput: 32_768,
    tier: 'efficient',
    strengths: ['ultra-fast', 'classification', 'extraction', 'cost-efficient'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['openai', 'nano', 'extraction'],
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    description: 'Modelo multimodal de OpenAI con capacidades creativas y generales.',
    contextWindow: 128_000,
    maxOutput: 16_384,
    tier: 'frontier',
    strengths: ['creative-writing', 'multimodal', 'general', 'vision'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['openai', 'multimodal', 'creative'],
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    description: 'Versión económica de GPT-4o para tareas generales de alta velocidad.',
    contextWindow: 128_000,
    maxOutput: 16_384,
    tier: 'efficient',
    strengths: ['cost-efficient', 'speed', 'general', 'tool-use'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['openai', 'efficient', 'general'],
  },
  {
    id: 'o3',
    name: 'OpenAI o3',
    provider: 'openai',
    description: 'Modelo de razonamiento profundo para matemáticas, ciencia y coding complejo.',
    contextWindow: 200_000,
    maxOutput: 100_000,
    tier: 'frontier',
    strengths: ['reasoning', 'math', 'science', 'coding'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['openai', 'reasoning', 'stem'],
  },
  {
    id: 'o3-mini',
    name: 'OpenAI o3 Mini',
    provider: 'openai',
    description: 'Razonamiento eficiente para STEM y coding a menor costo.',
    contextWindow: 200_000,
    maxOutput: 100_000,
    tier: 'mid',
    strengths: ['reasoning', 'cost-efficient', 'STEM', 'speed'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['openai', 'reasoning', 'efficient'],
  },
  {
    id: 'o3-pro',
    name: 'OpenAI o3 Pro',
    provider: 'openai',
    description: 'Máxima fiabilidad en razonamiento para tareas de alta complejidad.',
    contextWindow: 200_000,
    maxOutput: 100_000,
    tier: 'frontier',
    strengths: ['deep-reasoning', 'reliability', 'complex-tasks', 'research'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['openai', 'pro', 'reliability'],
  },
  {
    id: 'o4-mini',
    name: 'OpenAI o4 Mini',
    provider: 'openai',
    description: 'Razonamiento visual y coding rápido con capacidades multimodales.',
    contextWindow: 200_000,
    maxOutput: 100_000,
    tier: 'mid',
    strengths: ['reasoning', 'coding', 'visual-tasks', 'speed'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['openai', 'reasoning', 'visual'],
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'openai',
    description: 'Modelo legacy con JSON mode y visión, compatible con integraciones existentes.',
    contextWindow: 128_000,
    maxOutput: 4_096,
    tier: 'mid',
    strengths: ['legacy-compat', 'json-mode', 'vision', 'stability'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['openai', 'legacy', 'stable'],
  },
  // ─── Anthropic (7) ────────────────────────────────────────────────────
  {
    id: 'claude-sonnet-4',
    name: 'Claude Sonnet 4',
    provider: 'anthropic',
    description: 'Modelo principal de Anthropic para coding, instrucciones y seguridad.',
    contextWindow: 200_000,
    maxOutput: 64_000,
    tier: 'frontier',
    strengths: ['coding', 'instruction-following', 'safety', 'tool-use'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['anthropic', 'coding', 'safety'],
  },
  {
    id: 'claude-opus-4',
    name: 'Claude Opus 4',
    provider: 'anthropic',
    description: 'Razonamiento profundo, planificación y análisis de matices complejos.',
    contextWindow: 200_000,
    maxOutput: 32_000,
    tier: 'frontier',
    strengths: ['deep-reasoning', 'planning', 'nuance', 'analysis'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['anthropic', 'reasoning', 'planning'],
  },
  {
    id: 'claude-haiku-4',
    name: 'Claude Haiku 4',
    provider: 'anthropic',
    description: 'Ultra-rápido y económico para clasificación y extracción.',
    contextWindow: 200_000,
    maxOutput: 8_192,
    tier: 'efficient',
    strengths: ['speed', 'cost-efficient', 'classification', 'extraction'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['anthropic', 'fast', 'extraction'],
  },
  {
    id: 'claude-sonnet-3.5',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    description: 'Modelo balanceado para coding y análisis con buen costo-rendimiento.',
    contextWindow: 200_000,
    maxOutput: 8_192,
    tier: 'mid',
    strengths: ['coding', 'analysis', 'balanced', 'reliability'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['anthropic', 'balanced', 'coding'],
  },
  {
    id: 'claude-haiku-3.5',
    name: 'Claude 3.5 Haiku',
    provider: 'anthropic',
    description: 'Velocidad extrema para triage, extracción y tareas de alto volumen.',
    contextWindow: 200_000,
    maxOutput: 8_192,
    tier: 'efficient',
    strengths: ['ultra-fast', 'extraction', 'triage', 'high-volume'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['anthropic', 'fast', 'triage'],
  },
  {
    id: 'claude-sonnet-4.5',
    name: 'Claude Sonnet 4.5',
    provider: 'anthropic',
    description: 'Extended thinking para coding complejo y creatividad.',
    contextWindow: 200_000,
    maxOutput: 64_000,
    tier: 'frontier',
    strengths: ['extended-thinking', 'coding', 'creativity', 'long-output'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['anthropic', 'thinking', 'creative'],
  },
  {
    id: 'claude-opus-4.5',
    name: 'Claude Opus 4.5',
    provider: 'anthropic',
    description: 'Máxima capacidad de razonamiento para investigación y tareas de largo aliento.',
    contextWindow: 200_000,
    maxOutput: 32_000,
    tier: 'frontier',
    strengths: ['complex-reasoning', 'long-form', 'research', 'depth'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['anthropic', 'research', 'depth'],
  },
  // ─── Google (6) ───────────────────────────────────────────────────────
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    description: 'Modelo de razonamiento con 1M de contexto, multimodal y soporte nativo de MCP.',
    contextWindow: 1_000_000,
    maxOutput: 65_536,
    tier: 'frontier',
    strengths: ['reasoning', 'long-context', 'multimodal', 'mcp-native'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['google', 'reasoning', 'mcp'],
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    description: 'Velocidad y contexto largo a bajo costo para tareas generales.',
    contextWindow: 1_000_000,
    maxOutput: 65_536,
    tier: 'mid',
    strengths: ['speed', 'cost-efficient', 'large-context', 'general'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['google', 'fast', 'balanced'],
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    description: 'Multimodal rápido con capacidades agénticas y 1M de contexto.',
    contextWindow: 1_000_000,
    maxOutput: 8_192,
    tier: 'efficient',
    strengths: ['speed', 'multimodal', 'agentic', 'cost-efficient'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['google', 'agentic', 'fast'],
  },
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    provider: 'google',
    description: 'Ultra-rápido para alto throughput y tareas masivas.',
    contextWindow: 1_000_000,
    maxOutput: 8_192,
    tier: 'efficient',
    strengths: ['ultra-fast', 'high-throughput', 'cost', 'batch'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['google', 'batch', 'throughput'],
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    description: 'Contexto de 2M tokens para video, audio y documentos extensos.',
    contextWindow: 2_000_000,
    maxOutput: 8_192,
    tier: 'mid',
    strengths: ['ultra-long-context', 'video', 'audio', 'documents'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['google', 'long-context', 'video'],
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'google',
    description: 'Rápido y económico para summarización y tareas de contexto largo.',
    contextWindow: 1_000_000,
    maxOutput: 8_192,
    tier: 'efficient',
    strengths: ['speed', 'cost', 'summarization', 'long-context'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['google', 'summarization', 'fast'],
  },
  // ─── Meta / Llama (5) ───────────────────────────────────────────────
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'meta',
    description: 'Modelo MoE de 128 expertos con 1M de contexto, multilingüe y open-weight.',
    contextWindow: 1_000_000,
    maxOutput: 16_384,
    tier: 'frontier',
    strengths: ['multilingual', 'reasoning', 'open-weight', 'moe'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['meta', 'open-weight', 'moe'],
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'meta',
    description: 'Contexto de 10M tokens para análisis masivo de documentos.',
    contextWindow: 10_000_000,
    maxOutput: 16_384,
    tier: 'frontier',
    strengths: ['ultra-long-context', 'document-analysis', 'open-weight', 'research'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['meta', 'ultra-context', 'analysis'],
  },
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    provider: 'meta',
    description: 'Modelo open-weight de 70B para coding y self-hosting.',
    contextWindow: 128_000,
    maxOutput: 4_096,
    tier: 'mid',
    strengths: ['coding', 'open-weight', 'self-host', 'general'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['meta', 'self-host', 'coding'],
  },
  {
    id: 'llama-3.1-405b',
    name: 'Llama 3.1 405B',
    provider: 'meta',
    description: 'El modelo open-weight más grande de Meta, multilingüe y de uso general.',
    contextWindow: 128_000,
    maxOutput: 4_096,
    tier: 'frontier',
    strengths: ['open-weight', 'multilingual', 'general', 'scale'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['meta', 'large', 'multilingual'],
  },
  {
    id: 'llama-3.1-8b',
    name: 'Llama 3.1 8B',
    provider: 'meta',
    description: 'Modelo compacto para edge, fine-tuning y ejecución local.',
    contextWindow: 128_000,
    maxOutput: 4_096,
    tier: 'local',
    strengths: ['self-host', 'edge', 'fine-tuning', 'lightweight'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    localOnly: true,
    tags: ['meta', 'local', 'edge'],
  },
  // ─── Mistral (5) ────────────────────────────────────────────────────
  {
    id: 'mistral-large',
    name: 'Mistral Large 2',
    provider: 'mistral',
    description: 'Modelo flagship de Mistral para razonamiento, multilingüe y hosting europeo.',
    contextWindow: 128_000,
    maxOutput: 8_192,
    tier: 'frontier',
    strengths: ['reasoning', 'multilingual', 'coding', 'eu-hosted'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['mistral', 'eu', 'reasoning'],
  },
  {
    id: 'mistral-medium',
    name: 'Mistral Medium',
    provider: 'mistral',
    description: 'Modelo balanceado para business y aplicaciones multilingües.',
    contextWindow: 32_000,
    maxOutput: 8_192,
    tier: 'mid',
    strengths: ['balanced', 'business', 'multilingual', 'reliability'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['mistral', 'business', 'balanced'],
  },
  {
    id: 'mistral-small',
    name: 'Mistral Small',
    provider: 'mistral',
    description: 'Rápido y económico para extracción y tareas de alto volumen.',
    contextWindow: 128_000,
    maxOutput: 8_192,
    tier: 'efficient',
    strengths: ['speed', 'cost', 'extraction', 'high-volume'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['mistral', 'fast', 'extraction'],
  },
  {
    id: 'codestral',
    name: 'Codestral',
    provider: 'mistral',
    description: 'Especializado en coding con 256K de contexto y fill-in-the-middle.',
    contextWindow: 256_000,
    maxOutput: 8_192,
    tier: 'mid',
    strengths: ['coding', 'code-completion', 'fill-in-middle', 'long-context'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['mistral', 'coding', 'fim'],
  },
  {
    id: 'mistral-nemo',
    name: 'Mistral Nemo',
    provider: 'mistral',
    description: 'Modelo open-weight de 12B bajo Apache-2.0, ideal para self-hosting.',
    contextWindow: 128_000,
    maxOutput: 4_096,
    tier: 'efficient',
    strengths: ['open-weight', 'self-host', 'apache-2.0', 'compact'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['mistral', 'open', 'self-host'],
  },
  // ─── DeepSeek (3) ───────────────────────────────────────────────────
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    description: 'MoE open-weight para coding y matemáticas a muy bajo costo.',
    contextWindow: 128_000,
    maxOutput: 8_192,
    tier: 'mid',
    strengths: ['coding', 'math', 'open-weight', 'cost-efficient'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['deepseek', 'coding', 'math'],
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    description: 'Razonamiento con chain-of-thought explícito, open-weight.',
    contextWindow: 128_000,
    maxOutput: 8_192,
    tier: 'frontier',
    strengths: ['reasoning', 'chain-of-thought', 'math', 'open-weight'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['deepseek', 'reasoning', 'cot'],
  },
  {
    id: 'deepseek-coder-v2',
    name: 'DeepSeek Coder V2',
    provider: 'deepseek',
    description: 'Modelo MoE de 236B especializado en generación de código.',
    contextWindow: 128_000,
    maxOutput: 8_192,
    tier: 'mid',
    strengths: ['code-generation', 'moe', 'open-weight', 'multilingual'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['deepseek', 'coder', 'moe'],
  },
  // ─── Cohere (3) ─────────────────────────────────────────────────────
  {
    id: 'command-r-plus',
    name: 'Command R+',
    provider: 'cohere',
    description: 'Optimizado para RAG enterprise, multilingüe con grounding.',
    contextWindow: 128_000,
    maxOutput: 4_096,
    tier: 'frontier',
    strengths: ['rag', 'multilingual', 'enterprise', 'grounding'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['cohere', 'rag', 'enterprise'],
  },
  {
    id: 'command-r',
    name: 'Command R',
    provider: 'cohere',
    description: 'RAG eficiente con tool-use a menor costo.',
    contextWindow: 128_000,
    maxOutput: 4_096,
    tier: 'mid',
    strengths: ['rag', 'tool-use', 'cost-efficient', 'multilingual'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    tags: ['cohere', 'rag', 'balanced'],
  },
  {
    id: 'embed-v4',
    name: 'Embed v4',
    provider: 'cohere',
    description: 'Modelo de embeddings multilingüe para búsqueda y clustering.',
    contextWindow: 512,
    maxOutput: 0,
    tier: 'efficient',
    strengths: ['embeddings', 'search', 'clustering', 'multilingual'],
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: false,
    tags: ['cohere', 'embeddings', 'search'],
  },
  // ─── Open-source / Local (6) ────────────────────────────────────────
  {
    id: 'qwen-2.5-coder-32b',
    name: 'Qwen 2.5 Coder 32B',
    provider: 'open-source',
    description: 'Modelo de coding open-weight de Alibaba para self-hosting.',
    contextWindow: 131_072,
    maxOutput: 8_192,
    tier: 'local',
    strengths: ['coding', 'open-weight', 'self-host', 'multilingual'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    localOnly: true,
    tags: ['qwen', 'coding', 'local'],
  },
  {
    id: 'phi-4',
    name: 'Phi-4',
    provider: 'open-source',
    description: 'Modelo compacto de Microsoft especializado en razonamiento.',
    contextWindow: 16_384,
    maxOutput: 4_096,
    tier: 'local',
    strengths: ['reasoning', 'small-model', 'edge', 'efficient'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    localOnly: true,
    tags: ['microsoft', 'small', 'reasoning'],
  },
  {
    id: 'gemma-2-27b',
    name: 'Gemma 2 27B',
    provider: 'open-source',
    description: 'Modelo open-weight de Google para fine-tuning y experimentación.',
    contextWindow: 8_192,
    maxOutput: 4_096,
    tier: 'local',
    strengths: ['open-weight', 'fine-tuning', 'research', 'google'],
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: true,
    localOnly: true,
    tags: ['google', 'fine-tuning', 'local'],
  },
  {
    id: 'yi-1.5-34b',
    name: 'Yi 1.5 34B',
    provider: 'open-source',
    description: 'Contexto de 200K tokens, multilingüe y open-weight.',
    contextWindow: 200_000,
    maxOutput: 4_096,
    tier: 'local',
    strengths: ['long-context', 'multilingual', 'open-weight', 'versatile'],
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
    localOnly: true,
    tags: ['yi', 'long-context', 'multilingual'],
  },
  {
    id: 'starcoder-2-15b',
    name: 'StarCoder 2 15B',
    provider: 'open-source',
    description: 'Modelo open de BigCode para code-completion y fill-in-middle.',
    contextWindow: 16_384,
    maxOutput: 4_096,
    tier: 'local',
    strengths: ['code-completion', 'fill-in-middle', 'open-weight', 'bigcode'],
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: true,
    localOnly: true,
    tags: ['bigcode', 'completion', 'local'],
  },
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5 (Moonshot)',
    provider: 'open-source',
    description: 'Contexto de 1M tokens con multimodalidad a costo eficiente.',
    contextWindow: 1_000_000,
    maxOutput: 16_384,
    tier: 'mid',
    strengths: ['ultra-long-context', 'cost-efficient', 'multimodal', 'general'],
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
    tags: ['moonshot', 'long-context', 'multimodal'],
  },
];

// ─── Lookup and filter ──────────────────────────────────────────────────

const modelIndex = new Map(modelsCatalog.map((item) => [item.id, item]));

const fullModelsResponse = Object.freeze({
  version: MODELS_CATALOG_VERSION,
  items: modelsCatalog,
});

export function getModelById(id: string): ModelCatalogItem | undefined {
  return modelIndex.get(id);
}

export function getModelsCatalog(filter?: { provider?: string; tier?: string; q?: string }): {
  version: string;
  items: ModelCatalogItem[];
} {
  if (!filter?.provider && !filter?.tier && !filter?.q) {
    return fullModelsResponse;
  }
  let items = modelsCatalog;
  if (filter?.provider) {
    items = items.filter((item) => item.provider === filter.provider);
  }
  if (filter?.tier) {
    items = items.filter((item) => item.tier === filter.tier);
  }
  if (filter?.q) {
    const q = filter.q.toLowerCase();
    items = items.filter(
      (item) =>
        item.name.toLowerCase().includes(q) ||
        item.description.toLowerCase().includes(q) ||
        item.tags.some((tag) => tag.includes(q)),
    );
  }
  return { version: MODELS_CATALOG_VERSION, items };
}
